# Generated by Django 3.0.6 on 2020-05-17 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MangoBankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.PositiveIntegerField()),
                ('iban', models.CharField(max_length=35)),
                ('bic', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_account_type', models.CharField(default='IBAN', max_length=10)),
                ('creation_date', models.DateTimeField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MangoDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(default='IDENTITY_PROOF', max_length=23)),
                ('did', models.PositiveIntegerField(default=0)),
                ('creation_date', models.DateTimeField()),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=9)),
                ('refusal_type', models.CharField(blank=True, max_length=25, null=True)),
                ('refusal_message', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MangoEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('created', models.DateTimeField()),
                ('authentic', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MangoPayIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piid', models.PositiveIntegerField(default=0)),
                ('creation_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('culture', models.CharField(default='EN', max_length=2)),
                ('statement_descriptor', models.CharField(default='', max_length=12)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired'), ('VALIDATED', 'Validated')], default='CREATED', max_length=9)),
                ('result_code', models.CharField(blank=True, max_length=6, null=True)),
                ('result_message', models.CharField(blank=True, max_length=255, null=True)),
                ('nature', models.CharField(default='', max_length=10)),
                ('transaction_type', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='MangoPreAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MangoRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MangoUBODeclaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MangoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('usertype', models.CharField(choices=[('NATURAL', 'Natural user'), ('LEGAL', 'Legal user')], max_length=7)),
                ('mid', models.PositiveIntegerField(default=0)),
                ('birthday', models.DateField()),
                ('nationality', models.CharField(default='DE', max_length=50)),
                ('country_of_residence', models.CharField(default='DE', max_length=50)),
                ('kyc_status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mangouser_mango_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='MangoBankWirePayIn',
            fields=[
                ('mangopayin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.MangoPayIn')),
                ('execution_type', models.CharField(max_length=50)),
                ('wire_reference', models.CharField(max_length=50)),
                ('wire_type', models.CharField(max_length=5)),
                ('iban', models.CharField(max_length=50)),
                ('bic', models.CharField(max_length=25)),
            ],
            bases=('payments.mangopayin',),
        ),
        migrations.CreateModel(
            name='MangoCardDirectPayIn',
            fields=[
                ('mangopayin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.MangoPayIn')),
            ],
            bases=('payments.mangopayin',),
        ),
        migrations.CreateModel(
            name='MangoDDWebPayIn',
            fields=[
                ('mangopayin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.MangoPayIn')),
                ('direct_debit_type', models.CharField(default='SOFORT', max_length=7)),
                ('return_url', models.URLField()),
                ('redirect_url', models.URLField(blank=True, null=True)),
                ('template_url', models.URLField()),
            ],
            bases=('payments.mangopayin',),
        ),
        migrations.CreateModel(
            name='MangoLegalUser',
            fields=[
                ('mangouser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.MangoUser')),
            ],
            bases=('payments.mangouser',),
        ),
        migrations.CreateModel(
            name='MangoNaturalUser',
            fields=[
                ('mangouser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.MangoUser')),
            ],
            bases=('payments.mangouser',),
        ),
        migrations.CreateModel(
            name='MangoWebPayIn',
            fields=[
                ('mangopayin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.MangoPayIn')),
                ('return_url', models.URLField(default='someurl.com/')),
                ('card_type', models.CharField(choices=[('CB_VISA_MASTERCARD', 'CB VISA MASTERCARD'), ('MAESTRO', 'Maestro'), ('DINERS', 'Diners'), ('AMEX', 'Amex'), ('MASTERPASS', 'Masterpass'), ('P24', 'P24'), ('IDEAL', 'Ideal'), ('PAYLIB', 'Paylib'), ('BCMC', 'Bcmc')], default='CB_VISA_MASTERCARD', max_length=20)),
                ('secure_mode', models.BooleanField(default=True)),
            ],
            bases=('payments.mangopayin',),
        ),
        migrations.CreateModel(
            name='MangoWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wid', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('iban', models.CharField(blank=True, max_length=50, null=True)),
                ('bic', models.CharField(blank=True, max_length=12, null=True)),
                ('alias_country', models.CharField(default='LU', max_length=2)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mangowallet_wid', to='payments.MangoUser')),
            ],
        ),
        migrations.CreateModel(
            name='MangoTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.PositiveIntegerField()),
                ('creation_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('fees', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(max_length=9)),
                ('result_code', models.CharField(blank=True, max_length=6, null=True)),
                ('result_message', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_author', to='payments.MangoUser')),
                ('cwid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credited_wallet_id', to='payments.MangoWallet')),
                ('dwid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debited_wallet_id', to='payments.MangoWallet')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_recipient', to='payments.MangoUser')),
            ],
        ),
        migrations.CreateModel(
            name='MangoPayOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poid', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_date', models.DateTimeField()),
                ('execution_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='CREATED', max_length=15)),
                ('result_code', models.PositiveIntegerField(blank=True, null=True)),
                ('result_message', models.CharField(blank=True, max_length=250, null=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mango_payout_author_id', to='payments.MangoUser')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mango_bankaccount', to='payments.MangoBankAccount')),
                ('dwid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mango_debited_wallet_id', to='payments.MangoWallet')),
            ],
        ),
        migrations.AddField(
            model_name='mangopayin',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mangopayin_mango_payin_author', to='payments.MangoUser'),
        ),
        migrations.AddField(
            model_name='mangopayin',
            name='cwid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mangopayin_mango_payin_cwid', to='payments.MangoWallet'),
        ),
        migrations.CreateModel(
            name='MangoPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.PositiveIntegerField()),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mango_page', to='payments.MangoDocument')),
            ],
        ),
        migrations.AddField(
            model_name='mangodocument',
            name='mid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mango_document', to='payments.MangoUser'),
        ),
        migrations.CreateModel(
            name='MangoCardRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('card_type', models.CharField(default='CB VISA MASTERCARD', max_length=20)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mango_card_reg', to='payments.MangoUser')),
            ],
        ),
        migrations.CreateModel(
            name='MangoCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.PositiveIntegerField(default=0)),
                ('expiration_date', models.PositiveSmallIntegerField(default=0)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('alias', models.CharField(default='', max_length=20)),
                ('provider', models.CharField(default='', max_length=15)),
                ('card_type', models.CharField(choices=[('CB_VISA_MASTERCARD', 'CB VISA MASTERCARD'), ('MAESTRO', 'Maestro'), ('DINERS', 'Diners'), ('AMEX', 'Amex'), ('MASTERPASS', 'Masterpass'), ('P24', 'P24'), ('IDEAL', 'Ideal'), ('PAYLIB', 'Paylib'), ('BCMC', 'Bcmc')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=False)),
                ('creation_date', models.PositiveIntegerField(default=0)),
                ('fingerprint', models.CharField(default='call update function', max_length=100)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mango_card', to='payments.MangoUser')),
            ],
        ),
        migrations.AddField(
            model_name='mangobankaccount',
            name='mid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mango_bank_account', to='payments.MangoUser'),
        ),
    ]
