# Generated by Django 3.0.6 on 2020-07-01 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20200517_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangoTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('culture', models.CharField(default='EN', max_length=2)),
                ('statement_descriptor', models.CharField(default='', max_length=12)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired'), ('VALIDATED', 'Validated')], default='CREATED', max_length=9)),
                ('result_code', models.CharField(blank=True, max_length=6, null=True)),
                ('result_message', models.CharField(blank=True, max_length=255, null=True)),
                ('nature', models.CharField(default='', max_length=10)),
                ('transaction_type', models.CharField(max_length=10)),
                ('cwid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mangotransaction_mango_payin_cwid', to='payments.MangoWallet')),
            ],
        ),
    ]
