# Generated by Django 3.0.6 on 2020-07-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_mangotransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangobankaccount',
            name='iban',
            field=models.CharField(help_text='Format should be a regular Iban format', max_length=35),
        ),
        migrations.AlterField(
            model_name='mangobankaccount',
            name='mid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mangocard',
            name='mid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mangocardregistration',
            name='mid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mangodocument',
            name='mid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
