# Generated by Django 3.0.4 on 2020-03-22 13:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200322_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('a66ac604-bcf2-4574-8506-9770ae34a277'), editable=False, primary_key=True, serialize=False),
        ),
    ]
