# Generated by Django 3.0.4 on 2020-03-22 13:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200322_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('6e64be45-d603-437c-bf4e-236673069739'), editable=False, primary_key=True, serialize=False),
        ),
    ]
