# Generated by Django 3.0.4 on 2020-03-28 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('confessions', '0002_auto_20200325_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('situation', models.TextField(blank=True, null=True)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('intensity', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('private', models.BooleanField(default=False)),
                ('likes', models.PositiveSmallIntegerField(default=0)),
                ('applauses', models.PositiveSmallIntegerField(default=0)),
                ('mehs', models.PositiveSmallIntegerField(default=0)),
                ('laughs', models.PositiveSmallIntegerField(default=0)),
                ('cries', models.PositiveSmallIntegerField(default=0)),
                ('nature', models.BooleanField(choices=[('good', 'Good'), ('bad', 'Bad')])),
            ],
            options={
                'ordering': ['-registered'],
            },
        ),
        migrations.RemoveField(
            model_name='good',
            name='category',
        ),
        migrations.RemoveField(
            model_name='good',
            name='user',
        ),
        migrations.AddField(
            model_name='category',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Bad',
        ),
        migrations.DeleteModel(
            name='Good',
        ),
        migrations.AddField(
            model_name='deed',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confessions.Category'),
        ),
        migrations.AddField(
            model_name='deed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
