# Generated by Django 3.0.4 on 2020-03-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0003_auto_20200328_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='deed',
            name='nature',
            field=models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad')], max_length=4),
        ),
    ]
