# Generated by Django 3.0.4 on 2020-04-29 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('confessions', '0005_auto_20200418_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflection',
            name='deed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reflection', to='confessions.Deed'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('deed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='confessions.Deed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('update', models.DateTimeField(auto_now=True)),
                ('deed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='confessions.Deed')),
            ],
        ),
    ]
