# Generated by Django 3.0.4 on 2020-05-02 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0006_auto_20200429_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='price',
            field=models.IntegerField(default=1.0),
        ),
        migrations.AlterField(
            model_name='collection',
            name='update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
