# Generated by Django 3.0.4 on 2020-05-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0007_auto_20200502_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deed',
            name='reflection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deed',
            name='intensity',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tiny'), (2, 'Easy'), (3, 'Casual'), (4, 'Hard'), (5, 'Mindblowing')]),
        ),
        migrations.DeleteModel(
            name='Reflection',
        ),
    ]
