# Generated by Django 3.0.6 on 2020-07-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0008_auto_20200502_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
