# Generated by Django 3.0.6 on 2020-08-10 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0009_deed_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='price',
            field=models.IntegerField(default=1.0),
        ),
        migrations.AddField(
            model_name='deed',
            name='update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
